version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.1
    working_directory: ~/repo

jobs:
  snyk-job:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Snyk CLI
          command: |
            sudo npm install -g snyk
            snyk auth $SNYK_TOKEN
      - run:
          name: Test with Snyk Open Source
          command: snyk test --all-projects
      - run:
          name: Test with Snyk Code
          command: snyk code test
      - run:
          name: Monitor with Snyk
          command: snyk monitor --all-projects

workflows:
  version: 2
  snyk-workflow:
    jobs:
      - snyk-job
