version: 2.1

executors:
  snyk-executor:
    docker:
      - image: cimg/node:18.17.0  # Ou a versão do Node que seu projeto usa
    working_directory: ~/repo

jobs:
  snyk_os_scan:
    executor: snyk-executor
    steps:
      - checkout
      - run:
          name: Install Snyk CLI
          command: |
            npm install -g snyk
      - run:
          name: Run Snyk Open Source Scan
          command: |
            npm install
            snyk auth "$SNYK_TOKEN"
            snyk test --org="$SNYK_ORG"
            snyk monitor --org="$SNYK_ORG"

  snyk_code_scan:
    executor: snyk-executor
    steps:
      - checkout
      - run:
          name: Install Snyk CLI
          command: |
            npm install -g snyk
      - run:
          name: Run Snyk Code Scan
          command: |
            snyk auth "$SNYK_TOKEN"
            snyk code test --org="$SNYK_ORG"

workflows:
  version: 2
  snyk-scans:
    jobs:
      - snyk_os_scan
      - snyk_code_scan


