version: 2.1

jobs:
  snyk_scan:
    docker:
      - image: cimg/node:18.17.1  # Imagem com Node.js
    steps:
      - checkout
      - run:
          name: Instalar Snyk CLI
          command: |
            wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
            chmod +x ./snyk
            sudo mv ./snyk /usr/local/bin/
      - run:
          name: Instalar dependências (caso existam)
          command: |
            if [ -f package.json ]; then
              npm install
            fi
      - run:
          name: Autenticar com Snyk
          command: |
            snyk config set endpoint=https://api.us.snyk.io
            snyk auth ${SNYK_TOKEN}
      - run:
          name: Snyk Open Source Scan
          command: |
            snyk test
            snyk monitor
      - run:
          name: Snyk Code Scan
          command: |
            snyk code test

workflows:
  snyk_workflow:
    jobs:
      - snyk_scan
